### ISSUE TITLE
1.2.0 will take effect after joint-bilateral

### ISSUE THREAD

**Issue by yeezylife** [Artoriuz/glsl-pixel-clipper#3]
![火の鳥 -HINOTORI- 04 (BS-hi 1280x720 x264 aac Stereo)- 00_00_58 392](https://github.com/Artoriuz/glsl-pixel-clipper/assets/30175425/ced0f480-d877-48f3-90b6-49bc1594da4a)

And that doesn't seem necessary...An all-in-one solution is nice, but maybe let users to decide which pass to anti-ringging?

**Comment by Isaacx123** [comment]
Each pass is clearly defined inside the shader file, just delete all between line 92 to line 159.
I know is not the most elegant solution but a solution it is.
